### ISSUE TITLE
edit_datasets

### ISSUE THREAD

**Issue by learnalbert** [Zhendong-Wang/Prompt-Diffusion#16]
Hello, from your edit_dataset file, it can be seen that the example_pair and image_query you constructed belong to the same prompt. Could this lead to their content being overly similar, potentially causing some unintended effects on the training results?

**Comment by Zhendong-Wang** [comment]
Hello, I also tried the version of sampling two compelte seeds (prompts) each time, one for examples and one for query-ouput pair. Both the two versions work on the current tasks. With more data and tasks, I think different prompts would help more.
